### ISSUE TITLE
cgroups::config::options wrong type?

### ISSUE THREAD

**Issue by rooty0** [seattle-biomed/puppet-cgroups#1]
So according to documentation "cgroups::config::options" should be as a hash. 

```
  cgroups::config::options:
    blabla: 1
    ssadas: 5
```

but in the config.pp I see this

```
validate_array($options)
```

and of course I'm getting following error:

```
==> default: Error: {"cfs_period_us"=>"2"} is not an Array.  It looks to be a Hash at /tmp/vagrant-puppet/modules-be897c4d40d9e94dadf022aab51dab05/cgroups/manifests/config.pp:12 on node monitor01.us-east-1b.public
==> default: Error: {"cfs_period_us"=>"2"} is not an Array.  It looks to be a Hash at /tmp/vagrant-puppet/modules-be897c4d40d9e94dadf022aab51dab05/cgroups/manifests/config.pp:12 on node monitor01.us-east-1b.public
```

Is the documentation is deprecated?

**Comment by rooty0** [comment]
just tried following 

```
cgroups::config::options:
  - cfs_period_us: '2'
```

and as a result got this:

```
$ cat cgconfig.conf
#
# This file is managed by puppet class cgroups::config
#


mount {
  cpu = /sys/fs/cgroup/cpu;
  cpuacct = /sys/fs/cgroup/cpuacct;
  cpuset = /sys/fs/cgroup/cpuset;
  devices = /sys/fs/cgroup/devices;
  memory = /sys/fs/cgroup/memory;
  freezer = /sys/fs/cgroup/freezer;
}

{"cfs_period_us"=>"2"}
```

But syntax is something like this 

```
group lab2 {
        cpu {
                cpu.rt_period_us="1000000";
                cpu.rt_runtime_us="0";
                cpu.shares="3";
        }
}
```

So I wondering, is this module completly messed up or I'm doing something wrong?

**Comment by apowers** [comment]
The documentation is wrong. If you look at the template it is printing out each option one per line. So it expects something like ['cpu.shares="3"', 'cfs_period_us="2"']

I don't have an explanation for this except that this was one of my very early modules and I did it wrong. I don't have access to this repo anymore so I can't fix it either. If you think you will use this module I could fix it in a fork.

**Comment by rooty0** [comment]
@apowers, 
got it, thank you

It definitely will be very useful if you will be able to fork and fix it. I'm going to use it, yes.

**Comment by apowers** [comment]
Try this: https://github.com/apowers/puppet-cgroups
I haven't done any functional tests so if it doesn't do what you expect please let me know.

**Comment by rooty0** [comment]
@apowers since yesterday I'm getting following error when module is invoked

```
expected ',' or ']' in array at '{
      "name": "pup'! at /tmp/vagrant-puppet/manifests-846018e2aa141a5eb79a64b4015fc5f3/default.pp:29 on node monitor01.local.public
```

where line 29 is:

```
    class { 'cgroups': }
```

I also tried to invoke this as

```
    include '::cgroups'
```

still getting the same error

**Comment by rooty0** [comment]
when I'm testing this with puppet 3 - it works, and in case of puppet 2.7 - i'm getting this error

**Comment by apowers** [comment]
Look at init.pp line 13; I think Puppet 2.7 doesn't like the trailing comma.

**Comment by rooty0** [comment]
nope :(
I also tried to remove trailing comma from service.pp, same error. Also I was playing with different versions of stdlib, doesn't seem related for me.

**Comment by rooty0** [comment]
oh my... nm, just figured out that it's conflicting with rundeck's puppet module... insane, spend so much time :(

**Comment by rooty0** [comment]
Hey @apowers 
I just sent you a pull request, minor changes

Also a template of configuration seems broken. Puppet generates following

```
#
# This file is managed by puppet class cgroups::config
#

mount {
  cpu = /sys/fs/cgroup/cpu;
  cpuacct = /sys/fs/cgroup/cpuacct;
  cpuset = /sys/fs/cgroup/cpuset;
  devices = /sys/fs/cgroup/devices;
  freezer = /sys/fs/cgroup/freezer;
  memory = /sys/fs/cgroup/memory;
}

group lab2 {
cpu {
cpu.rt_period_us = "1000000";
cpu.rt_runtime_us = "0";
cpu.shares = "3";
}
cpu = "cpu.rt_runtime_us0cpu.rt_period_us1000000cpu.shares3";
}
```

following string is unformated dublicate:

```
cpu = "cpu.rt_runtime_us0cpu.rt_period_us1000000cpu.shares3";
```

this is from hiera:

```
cgroups::config::ensure:  'present'
cgroups::service::ensure:  'running'
cgroups::service::enable:  'true'
cgroups::config::rules:
  - 'oracle    cpu,cpuset,memory    dbgrp'
  - '@guest    devices              devgrp'
  - '%:rm      devices              devgrp/rm'
cgroups::config::options:
  'group lab2':
      'cpu':
          'cpu.rt_period_us':  "1000000"
          'cpu.rt_runtime_us': "0"
          'cpu.shares':        "3"
```

**Comment by apowers** [comment]
Thanks. I'll fix the template tomorrow morning.

**Comment by rooty0** [comment]
Thank you!

**Comment by apowers** [comment]
Updated. See if that works.
For further bugs, please report them in the new repo so that we don't annoy
whoever is monitoring this one.

**Comment by rooty0** [comment]
I'll test it today, thank you!

> For further bugs, please report them in the new repo

Ok, make sense. The only one question, should I close this ticket or let's keep it open for people who will come from googling for this module so they will be able to find this ticket fast and to follow the link to your fork
